name: Staging Build

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        env:
          runtime: linux-x64
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Astromine Staging
          path: build/libs